# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [150, 100], mode: outbound }

        event_thumb:
            quality: 75
            filters:
                thumbnail: { size : [150, 70], mode: outbound }

        news_cover:
            quality: 75
            filters:
                thumbnail: { size: [730, 300], mode: outbound }

        map:
            quality: 75
            filters:
                thumbnail: { size: [600, 300], mode: outbound }