security:

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_MOD]
        ROLE_MOD: [ROLE_USER]

    providers:
        users:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\TwitchAuthenticator

            logout:
                path: /logout

            user_checker: App\Security\UserChecker

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_MOD] }
