vich_uploader:
    db_driver: orm

    mappings:
        map_image:
            uri_prefix: /images/maps
            upload_destination: '%kernel.project_dir%/public/images/maps'
            inject_on_load: true
            delete_on_remove: true
            delete_on_update: true

        map_download:
            uri_prefix: /download/maps
            upload_destination: '%kernel.project_dir%/public/download/maps'
            inject_on_load: true
            delete_on_remove: true
            delete_on_update: true