parameters:
    locale: 'en'

    twitch_private_key: 'd60amswbo3ybxguj4mzkbvv5jed5hi'
    twitch_public_key: 'o3nb4qfewluyxokbm1qrg0mx7cpnh2'
    twitch_redirect_url: 'http://localhost:8000/login-twitch'
    twitch_auth_url: 'https://id.twitch.tv/'
    twitch_channel_id : '2400710'

    youtube_data_key: 'AIzaSyCdii-VCfIqst6B1qvtIHXswXX_NaSz1QQ'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Twitch

    App\Service\Twitch\TwitchAuthenticationService:
        arguments:
            $privateKey: '%twitch_private_key%'
            $publicKey: '%twitch_public_key%'
            $redirectUrl: '%twitch_redirect_url%'
            $authUrl: '%twitch_auth_url%'
            $channelId: '%twitch_channel_id%'

    App\Service\Twitch\TwitchClipService:
        arguments:
            $clientId: '%twitch_public_key%'

    # Youtube

    App\Service\Youtube\YoutubeVideoService:
        arguments: ['@doctrine.orm.entity_manager', '%youtube_data_key%']

    app.admin_user_form:
        class: App\Form\Admin\AdminUserType
        arguments: ['@security.token_storage']
        tags:
          - { name: form.type }

    app.user_activity_listener:
        class: App\Listener\UserActivityListener
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }