parameters:
    locale: 'en'

    twitch_private_key: 'd60amswbo3ybxguj4mzkbvv5jed5hi'
    twitch_public_key: 'o3nb4qfewluyxokbm1qrg0mx7cpnh2'
    twitch_redirect_url: 'http://localhost:8000/login-twitch'
    twitch_auth_url: 'https://id.twitch.tv/'
    twitch_channel_id : '2400710'

    youtube_data_key: 'AIzaSyCdii-VCfIqst6B1qvtIHXswXX_NaSz1QQ'

    voobly_key: 'a2r4efoeim07t0ub2wryx05wjqodj4hj'

    file_event_dir: '%kernel.project_dir%/public/media/events'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Twitch

    App\Service\Twitch\TwitchAuthenticationService:
        arguments:
            $privateKey: '%twitch_private_key%'
            $publicKey: '%twitch_public_key%'
            $redirectUrl: '%twitch_redirect_url%'
            $authUrl: '%twitch_auth_url%'
            $channelId: '%twitch_channel_id%'

    App\Service\Twitch\TwitchClipService:
        arguments:
            $clientId: '%twitch_public_key%'

    App\Service\Twitch\TwitchStreamService:
        arguments:
            $clientId: '%twitch_public_key%'

    # Youtube

    App\Service\Youtube\YoutubeVideoService:
        arguments: ['@doctrine.orm.entity_manager', '%youtube_data_key%']

    # Voobly

    App\Service\Voobly\VooblyService:
        arguments:
            $key: '%voobly_key%'

    # Menus

    app.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@security.token_storage"]

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createMainMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main }


    app.admin_user_form:
        class: App\Form\Admin\AdminUserType
        arguments: ['@security.token_storage']
        tags:
          - { name: form.type }

    # Listeners

    app.user_activity_listener:
        class: App\Listener\UserActivityListener
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }